//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string sex { get; set; }
        public string telephone { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<int> actived { get; set; }
        public string code { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
